# Generated by Django 4.0.1 on 2022-01-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='person',
            new_name='Person',
        ),
    ]
