# Generated by Django 4.0.1 on 2022-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_rename_person_group_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Person',
            field=models.ManyToManyField(related_name='persons_in_group', through='all.Membership', to='all.Person'),
        ),
    ]
