# Generated by Django 4.0.1 on 2022-01-31 22:51

from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_alter_group_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.query.prefetch_related_objects, to='all.group'),
        ),
    ]
