# Generated by Django 4.0.1 on 2022-02-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_alter_membership_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.group'),
        ),
    ]
